version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cryptokey_db_2
      POSTGRES_USER: cryptokey_user_2
      POSTGRES_PASSWORD: GioTest123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - cryptokey_network

  web:
    build:
      context: ./cryptokey_project2
    command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    networks:
      - cryptokey_network
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./crypto_key
      args:
        API_URL: "http://localhost:8000/api"
    ports:
      - "80:80"
    networks:
      - cryptokey_network
    depends_on:
      - web

networks:
  cryptokey_network:

volumes:
  postgres_data:
