version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: cryptokey_db_2
      POSTGRES_USER: cryptokey_user_2
      POSTGRES_PASSWORD: GioTest123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - cryptokey_network

  web:
    build:
      context: ./cryptokey_project2
    command: /app/wait_for_db.sh python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: GioTest123
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    networks:
      - cryptokey_network
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./crypto_key
      args:
        API_URL: "https://cryptokey.lebourbier.be/api"
    ports:
      - "80:80"
    networks:
      - cryptokey_network
    volumes:
      - ./crypto_key/build/web:/usr/share/nginx/html
    depends_on:
      - web

networks:
  cryptokey_network:

volumes:
  postgres_data:
