# Generated by Django 5.0.6 on 2024-06-08 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitycard',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='identitycard',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='identitycard',
            name='date_of_issue',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='identitycard',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='identitycard',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='identitycard',
            name='surname',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='identitycard',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='identitycard',
            name='id_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
