# Generated by Django 5.0.6 on 2024-06-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_identitycard_issued_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptionkey',
            name='titles',
            field=models.TextField(default='Unknown', max_length=255),
        ),
    ]
