# Generated by Django 5.0.6 on 2024-06-09 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_encryptionkey_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passwordentry')),
                ('shared_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_user', to=settings.AUTH_USER_MODEL)),
                ('shared_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('password_entry', 'shared_with_user', 'shared_by_user')},
            },
        ),
    ]
