# Generated by Django 5.0.6 on 2024-07-28 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passwordshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryptionkey',
            old_name='key',
            new_name='encrypted_key',
        ),
        migrations.RenameField(
            model_name='securenote',
            old_name='content',
            new_name='encrypted_content',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='identitycard',
            name='id_number',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='encrypted_card_number',
            field=models.CharField(default='default_value', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identitycard',
            name='encrypted_id_number',
            field=models.CharField(default='default_value', max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
