name: flutter_kryptokey_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  encrypt: ^5.0.0
  flutter_secure_storage: ^9.2.2
  flutter_datetime_picker: ^1.5.1
  http: ^1.2.1
  fl_chart: ^0.68.0
  jwt_decode: 0.3.1
  intl: ^0.19.0
  path_provider: ^2.0.11
  open_file: ^3.0.1
  cryptography: ^2.7.0
  file_picker: ^5.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
