name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-with-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker image for crypto_key
        run: docker build -t myapp-trivy-crypto-key ./crypto_key

      - name: Build Docker image for cryptokey_project2
        run: docker build -t myapp-trivy-cryptokey-project2 ./cryptokey_project2

      - name: Scan Docker image with Trivy (crypto_key)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp-trivy-crypto-key

      - name: Scan Docker image with Trivy (cryptokey_project2)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp-trivy-cryptokey-project2

  scan-with-clair:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker image for crypto_key
        run: docker build -t myapp-clair-crypto-key ./crypto_key

      - name: Build Docker image for cryptokey_project2
        run: docker build -t myapp-clair-cryptokey-project2 ./cryptokey_project2

      - name: Install Clairctl
        run: |
          curl -L https://github.com/quay/clairctl/releases/download/v1.2.10/clairctl-linux-amd64 -o clairctl
          chmod +x clairctl
          sudo mv clairctl /usr/local/bin/
          

      - name: Scan Docker image with Clair (crypto_key)
        run: |
          docker run -d --name clair -p 6060:6060 -p 6061:6061 quay.io/projectquay/clair:4.7.4
          clairctl analyze myapp-clair-crypto-key

      - name: Scan Docker image with Clair (cryptokey_project2)
        run: |
          docker run -d --name clair -p 6060:6060 -p 6061:6061 quay.io/projectquay/clair:4.7.4
          clairctl analyze myapp-clair-cryptokey-project2

  scan-with-snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snyk
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install Python dependencies for Django
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r cryptokey_project2/requirements.txt

      - name: Test for vulnerabilities in Python dependencies
        run: snyk test --file=cryptokey_project2/requirements.txt --package-manager=pip
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  scan-with-owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Run web application
        run: docker-compose up -d

      - name: Scan with OWASP ZAP
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8000'
