name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-flutter-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3' # Assurez-vous que c'est la version correcte

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web app
        run: flutter build web

  scan-with-trivy:
    runs-on: ubuntu-latest
    needs: build-flutter-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t myapp-trivy -f crypto_key/Dockerfile .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp-trivy

  scan-with-clair:
    runs-on: ubuntu-latest
    needs: build-flutter-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t myapp-clair -f crypto_key/Dockerfile .

      - name: Install Clairctl
        run: |
          curl -L https://github.com/jgsqware/clairctl/releases/download/v1.2.10/clairctl-linux-amd64 -o clairctl
          chmod +x clairctl
          sudo mv clairctl /usr/local/bin/

      - name: Scan Docker image with Clair
        run: |
          docker run -d --name clair -p 6060:6060 -p 6061:6061 quay.io/coreos/clair:v2.1.1
          clairctl analyze myapp-clair

  scan-with-snyk:
    runs-on: ubuntu-latest
    needs: build-flutter-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snyk
        uses: snyk/actions/setup@v1
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install Python dependencies for Django
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r cryptokey_project2/requirements.txt

      - name: Test for vulnerabilities in Python dependencies
        run: snyk test --file=cryptokey_project2/requirements.txt --package-manager=pip

  scan-with-owasp-zap:
    runs-on: ubuntu-latest
    needs: build-flutter-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Run web application
        run: docker-compose up -d

      - name: Scan with OWASP ZAP
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:8000'
